name:                diagrams-braille
version:             0.1.0.2
github:              "mlang/diagrams-braille"
license:             BSD3
author:              "Mario Lang"
maintainer:          "mlang@blind.guru"
copyright:           "2018 Mario Lang"

extra-source-files:
- README.md

synopsis:            Braille diagrams with plain text
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README at <https://github.com/mlang/diagrams-braille#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- diagrams-lib >= 1.4 && < 1.5
- diagrams-core >= 1.4 && < 1.5
- diagrams-rasterific >= 1.4 && < 1.5
- filepath
- hashable
- JuicyPixels
- mtl
- lens
- optparse-applicative
- Rasterific >= 0.7.4 && < 0.8
- time

library:
  source-dirs: src

executables:
  brldia:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams-braille
